### ISSUE TITLE
Tutorial: DWN (generate DID, write to DWN...)

### ISSUE THREAD

**Issue by ALRubinger** [TBD54566975/docs-sitemap#10]
Based on list provided by @bobbilee19:

1. Generate a DID, store private keys
2. Set up local DWN (instantiate DWN)
3. Write first record to DWN
4. Usage of record interface method
5. Protocols

ALR assign to Frank when TBD54566975/developer.tbd.website#13 is fixed

**Comment by ALRubinger** [comment]
Moving from the developer.tbd.website repo; to @bobbilee19 to see it's still valid or encapsulated in other issues. Housekeeping the project board. :)

**Comment by bobbilee19** [comment]
This is to come later since we may not have this in the new DWN docs?

**Comment by ALRubinger** [comment]
Makes sense to me - looking for guidance from the DWN core devs when they're ready to document standalone DWN usage, rather than via Web5. Could also be a great section to talk about standing up your own DWN, or one-click install from a DWN in a cloud provider, etc. Bumping to next phases sounds right while we work these out.

**Comment by angiejones** [comment]
The work for this task was completed at the Austin offsite

**Comment by ALRubinger** [comment]
+1 @angiejones - this is repurposed into materials under the "Build" section, and some are already deployed and written by @chris-tbd under `docs/web5/build/decentralized-identifiers`.
