### ISSUE TITLE
Discussion: Identify Personas

### ISSUE THREAD

**Issue by ALRubinger** [TBD54566975/docs-sitemap#3]

**Comment by ALRubinger** [comment]
First working session notes and the beginnings of a framework to be fleshed out enough for broader team input by end of week: https://hackmd.io/h0JTlrdZQnCXfxl8lmckiQ

Props to our community contributors Syd and Tania for their perspectives and working through this with us! Really leveled up the conversation and brought both validation and divergent ideas we need to incorporate.

We'll put this Markdown into the GitHub repo for more input when its gone through another round or 2 of structure.

**Comment by ALRubinger** [comment]
Summary of today's session (lifted from [Discord](https://discord.com/channels/937858703112155166/949067751803191397/1080287526583021618)): 

By end of week we should have a draft framework for:
* Identifying the types of audiences we serve
* ...and their goals
* ...relative to their position on the "engagement ladder" - how far along in their journey they are
* ...with how we'll have content and docs to help them reach their goals or move up the ladder
* ...and ways to measure how effective we're being at the above.

We expect that framework will drive clarity about the site decisions we make, and leave room for all stakeholders to surface their needs.

**Comment by ALRubinger** [comment]
Next step: @ALRubinger to propose a thought model, a framework through which we can address all the above

**Comment by angiejones** [comment]
really good model!

**Comment by ALRubinger** [comment]
Consensus from sync call today w/ @ALRubinger @dayhaysoos @angiejones @bobbilee19 @kirahsapong - Model looks good, content we can still work on. NICE!

**Comment by nearlyjuly** [comment]
Going by observation I think these are the interested parties
1. people who want to set up their own dwn + configure their own storage + their own hosting
2. people who want their own dwn with some or all of the above sorted out for them
3. hosting providers who want to provide a full solution or a package for setting up and using a dwn
4. SSI tools for those who want to do it all themselves
5. SSI solutions for those who want to press buttons and get what they need out
6. wallet providers who want to know where they fit in
7. app creators who want to know how to apply their existing skills to plumb into the above
8. GDPR/compliance/other professions who need to know how personal data is moved about and how access is configured
9. Key management/solutions providers who want to support all the above
10. Recruitment who need to know who to hire for all the above

**Comment by bobbilee19** [comment]
@ALRubinger we haven't spoken about persona's in awhile or about creating different pages depending on who we're talking to. I think we should probably talk about adding this to the agenda orrrr we just get out our first drafts of the docs for now and revisit this next quarter? we table for now,

**Comment by ALRubinger** [comment]
@bobbilee19 Sounds about right - I think introducing the emerging personas framework makes sense for F2F. Because we're there principally to bootstrap one archetype: the _Web5 Application Builders_ who are _Ready to Get Started_. But we recognize that's not the whole story of the purpose of the Developer Program or developer.tbd.website - so as you suggest, let's prime those later discussions and get on the same page with current, short-term, long term audiences. Great note on surveys and expanding; pretty pumped for Community Manager to be starting.

**Comment by ALRubinger** [comment]
This is sufficient for Phase 2 direction and we'll build out more with other teams and Leads as they join.
