### ISSUE TITLE
Templates for Content Types

### ISSUE THREAD

**Issue by ALRubinger** [TBD54566975/docs-sitemap#6]
Content types are defined in #5, likely a prereq for this issue.

For each documentation type, create a template that folks (primarily OSE Project Docs DRIs) can fill out and work with DevRel and others to get their project docs reflected.

May be broken into subtasks per content type as defined by #5.

**Comment by bobbilee19** [comment]
Progress is going to be made on this tonight and tomorrow, just checking in here. 

I'm going to prep templates for the following (into the sitemap repo):
1. Introduction / Overview page (for each project)

2. Quickstart for each project

3. Tutorials (longer written out case study / topic based tutorials, longer than quickstarts)

4. Any follow-up general topic based pages for certain topics that are within each project
Sample Apps (list page, where someone could list out templates)

6. Release notes

As for Sandbox/Playground: I do see these being embedded into the API techref pages, so let's circle back on this once we have more sandbox examples built etc. I see this not being in phase 1.
